[project]
name = "code-scraping-jurnal-unikom"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "mysql>=0.0.3",
    "mysql-connector-python>=9.5.0",
    "pandas>=3.0.0",
    "seaborn>=0.13.2",
    "sqlalchemy>=2.0.46",
]
